# frozen_string_literal: true

require "yaml"
require "json"
require_relative "runtime"

module Keiyaku
  # Turns an OpenAPI document into three files: value types, a client, and RBS.
  #
  # The guiding rule is that anything it cannot translate faithfully becomes a
  # loud refusal rather than plausible-looking code.
  class Emitter
    Refusal = Struct.new(:operation, :reason)

    # One Data subclass to be emitted. `fields` maps the Ruby name to the Ruby
    # source for its type, `from` to the JSON name where the two differ. Being
    # a value, two of these built from the same schema compare equal, which is
    # what lets an inline schema appearing twice be emitted once.
    Model = Data.define(:fields, :required, :from)

    # Stamped on every file it writes: which generator, and which version of
    # the runtime contract the code was written against.
    HEADER = "# Generated by keiyaku #{VERSION}. Edits will be overwritten."

    SCALARS = {
      %w[string date-time] => "Time",
      %w[string date] => "Date",
      %w[string binary] => "String",
      %w[string] => "String",
      %w[integer] => "Integer",
      %w[number] => "Float",
      %w[boolean] => ":bool"
    }.freeze

    # OpenAPI describes no pagination, so there is nothing to detect: guessing
    # from parameter names called `page` or `cursor` would produce a client
    # that loops wrongly and silently. The document has to say so itself, in
    # an x-keiyaku-paginate extension on the operation.
    PAGINATION = %w[offset page cursor link].freeze

    attr_reader :refusals, :notes

    def initialize(path, namespace:)
      @spec = path.end_with?(".json") ? JSON.parse(File.read(path)) : YAML.load_file(path)
      @namespace = namespace
      @models = {}      # constant name => args for Keiyaku.model(...), or union source
      @unions = {}      # union source => its RBS expansion, e.g. "Dog | Cat"
      @deps = {}        # constant name => referenced constant names
      @refusals = []
      @notes = []
    end

    def emit(dir)
      collect_models
      operations = collect_operations
      File.write(File.join(dir, "types.rb"), types_source)
      File.write(File.join(dir, "client.rb"), client_source(operations))
      File.write(File.join(dir, "#{Keiyaku.snake(@namespace)}.rbs"), rbs_source(operations))
      operations
    end

    private

    def resolve(node)
      return node unless node.is_a?(Hash) && node["$ref"]

      node["$ref"].delete_prefix("#/").split("/").reduce(@spec) { |doc, key| doc.fetch(key) }
    end

    def const_for(ref) = ref.split("/").last.gsub(/[^a-zA-Z0-9]/, "")

    # --- schemas ------------------------------------------------------------

    def collect_models
      (@spec.dig("components", "schemas") || {}).each do |name, schema|
        define_model(const_for(name), schema)
      end
    end

    # `upload:` is set while translating a multipart body, where a binary
    # string means a file rather than a String.
    def define_model(const, schema, upload: false)
      schema = merge_all_of(schema)

      # A component that is itself a union is not a Data subclass; it is a
      # constant holding the union, so that a $ref to it still resolves.
      if schema["oneOf"] || schema["anyOf"]
        deps = []
        source = collapse_union(schema, const, deps)
        expansion = source ? rbs_type(source) : nil
        source, expansion = union_for(schema, const, deps) unless source

        @models[const] = source
        @unions[const] = expansion
        @deps[const] = deps.uniq - [const]
        return
      end

      deps = []
      @models[const] = build_model(const, schema, deps, upload:)
      @deps[const] = deps.uniq - [const]
    end

    # Builds the model without deciding what it is called, so that a caller can
    # compare it against the ones already emitted.
    def build_model(const, schema, deps, upload: false)
      declared = schema["required"] || []
      fields, required, from = {}, [], {}

      (schema["properties"] || {}).each do |json_name, property|
        field = Keiyaku.snake(json_name)
        if fields.key?(field)
          @notes << "#{const}: #{json_name.inspect} and another property both become #{field}, keeping the first"
          next
        end

        fields[field] = type_for(property, "#{const}.#{field}", deps, upload:)
        required << field if declared.include?(json_name)
        from[field] = json_name if Keiyaku.camelize(field) != json_name
      end

      Model.new(fields:, required:, from:)
    end

    def merge_all_of(schema)
      return schema unless schema["allOf"]

      schema["allOf"].map { merge_all_of(resolve(_1)) }.reduce(schema.except("allOf")) do |acc, part|
        acc.merge(part) do |key, a, b|
          case key
          when "properties" then a.merge(b)
          when "required" then a | b
          else b
          end
        end
      end
    end

    # Returns Ruby source for a type, recording model dependencies as it goes.
    def type_for(schema, context, deps, upload: false)
      return ":any" if schema.nil? || schema.empty?

      if (ref = schema["$ref"])
        const = const_for(ref)
        deps << const
        return const
      end

      schema = merge_all_of(schema) if schema["allOf"]

      if schema["oneOf"] || schema["anyOf"]
        collapsed = collapse_union(schema, context, deps)
        return collapsed if collapsed

        source, expansion = union_for(schema, context, deps)
        @unions[source] = expansion unless source == ":any"
        return source
      end

      case schema["type"]
      when "array"
        # A tuple — `items` as a list in draft-07, `prefixItems` in 2020-12 —
        # is a fixed-length heterogeneous array, which one element type cannot
        # describe. Taking the first element's type would be a guess.
        if schema["items"].is_a?(Array) || schema["prefixItems"]
          @notes << "#{context}: a tuple, typed as [:any]"
          return "[:any]"
        end

        # An array of files is a real multipart shape, so `upload:` carries
        # into the items — but not into a nested object, where a part is JSON
        # and a file would be meaningless.
        "[#{type_for(schema["items"] || {}, "#{context}[]", deps, upload:)}]"
      when "object", nil
        if (additional = schema["additionalProperties"]).is_a?(Hash)
          "{ String => #{type_for(additional, "#{context}{}", deps)} }"
        elsif schema["properties"]
          const = hoist(context, schema, deps)
          const || ":any"
        else
          ":any"
        end
      else
        format = [schema["type"], schema["format"]].compact
        if upload && format == %w[string binary]
          ":upload"
        else
          SCALARS[format] || SCALARS[[schema["type"]]] || ":any"
        end
      end
    end

    # Two shapes that are unions only on paper. `anyOf: [{type: string},
    # {type: null}]` is how OpenAPI 3.1 says a field may be null — the field is
    # a string — and a union whose branches all resolve to one type says
    # nothing that type does not. Neither is a guess: there is exactly one type
    # in it. Returns nil when the union is a real one.
    def collapse_union(schema, context, deps)
      variants = (schema["oneOf"] || schema["anyOf"]).reject { _1["type"] == "null" }
      return nil if variants.empty?
      return type_for(variants.first, context, deps) if variants.size == 1

      # With more than one left, deciding means translating them all, so this
      # only looks at branches that cannot hoist a model — otherwise comparing
      # them could leave behind a type nothing goes on to name.
      return nil unless variants.all? { _1.key?("$ref") || SCALARS.key?([_1["type"]]) }

      scratch = []
      sources = variants.map { type_for(_1, context, scratch) }
      return nil unless sources.uniq.size == 1

      deps.concat(scratch)
      sources.first
    end

    # A union translates only when the document says how to tell the variants
    # apart. Casting by trying each one until something sticks is exactly the
    # plausible-but-wrong behaviour this generator exists to avoid, so an
    # undiscriminated union stays :any and says why.
    #
    # Returns the Ruby source and the RBS that describes it.
    def union_for(schema, context, deps)
      keyword = schema["oneOf"] ? "oneOf" : "anyOf"
      variants = schema[keyword]
      property = schema.dig("discriminator", "propertyName")

      complaint =
        if property.nil? then "no discriminator"
        elsif !variants.all? { _1.key?("$ref") } then "a variant written inline"
        end
      if complaint
        @notes << "#{context}: #{keyword} with #{complaint}, typed as :any"
        return [":any", "untyped"]
      end

      consts = variants.map { const_for(_1["$ref"]) }
      mapping = (schema["discriminator"]["mapping"] || {}).map do |value, ref|
        [value, const_for(ref)]
      end
      deps.concat(consts + mapping.map(&:last))

      args = [*consts, "on: #{property.inspect}"]
      args << "map: { #{mapping.map { |value, const| "#{value.inspect} => #{const}" }.join(", ")} }" if mapping.any?
      ["Keiyaku::OneOf[#{args.join(", ")}]", (consts + mapping.map(&:last)).uniq.join(" | ")]
    end

    # An inline object gets its own type rather than degrading to a bare Hash,
    # named for where it appeared. A document that writes the same schema out
    # again under every operation — which is what one with no components looks
    # like — would otherwise get a model per copy, so an identical model that
    # has already been emitted is used instead of a second one.
    def hoist(context, schema, deps, upload: false)
      const = context.split(/[.\[\]{}]/).reject(&:empty?).map { |part| Keiyaku.camelize(part).sub(/\A./, &:upcase) }.join
      own = []
      model = build_model(const, merge_all_of(schema), own, upload:)

      if (existing = @models.key(model))
        deps << existing
        return existing
      end

      if @models.key?(const)
        @notes << "#{const} already names a different schema, so #{context} is typed :any"
        return nil
      end

      @models[const] = model
      @deps[const] = own.uniq - [const]
      deps << const
      const
    end

    # --- operations ---------------------------------------------------------

    def collect_operations
      if @spec.dig("servers", 0, "url").to_s.empty?
        @notes << "no servers declared; a client has to be built with base_url:"
      end

      schemes = @spec.dig("components", "securitySchemes") || {}
      @security = schemes.filter_map { |_, scheme| security_declaration(scheme) }.first
      if @security.nil? && schemes.any?
        @notes << "no supported security scheme (#{schemes.values.map { _1["type"] }.uniq.join(", ")}); " \
                  "the client sends no credentials"
      end

      operations = @spec["paths"].flat_map do |template, path_item|
        path_item.slice("get", "put", "post", "delete", "patch", "head", "options").map do |verb, op|
          build_operation(verb, template, op, path_item["parameters"] || [])
        end
      end

      # Two operations landing on one name would mean the second silently
      # replacing the first, which is a method that goes somewhere other than
      # where its name says.
      operations.group_by { _1[:name] }.each do |name, group|
        next if group.size == 1

        @notes << "#{name} names #{group.size} operations (#{group.map { "#{_1[:verb].upcase} #{_1[:template]}" }.join(", ")}); " \
                  "only the last is reachable"
      end

      operations
    end

    def security_declaration(scheme)
      case scheme.values_at("type", "scheme", "in")
      in ["http", "bearer", _] then ":bearer"
      in ["http", "basic", _] then ":basic"
      in ["apiKey", _, "header"] then "{ header: #{scheme["name"].inspect} }"
      else nil
      end
    end

    # An operationId is optional, and plenty of documents that a server
    # generates from its own routes carry none, so the verb and the path are
    # all there is to go on. A path parameter becomes `by_x`, which keeps
    # GET /pet and GET /pet/{petId} from arriving at the same method.
    def operation_name(verb, template, op)
      raw = op["operationId"] || "#{verb}_#{template.gsub(/\{(\w+)\}/) { "by_#{$1}" }}"

      # The separators have to become underscores before snake sees them: it
      # drops anything that is not a word character, which would run the
      # segments of a path together.
      Keiyaku.snake(raw.gsub(/[^a-zA-Z0-9]+/, "_")).squeeze("_").delete_prefix("_").delete_suffix("_")
    end

    def build_operation(verb, template, op, inherited_params)
      name = operation_name(verb, template, op)
      refuse = ->(reason) { @refusals << Refusal.new(name, reason); return { name:, unsupported: reason } }
      deps = []

      params = (inherited_params + (op["parameters"] || [])).map { resolve(_1) }
      query, header, types = [], {}, {}

      params.each do |param|
        style = param["style"] || (param["in"] == "query" ? "form" : "simple")
        explode = param.fetch("explode", style == "form")
        types[param["name"]] = type_for(param["schema"] || {}, "#{name}_#{Keiyaku.snake(param["name"])}", deps)

        case param["in"]
        when "path"
          return refuse.("path parameter #{param["name"]} uses style=#{style}") unless style == "simple"
        when "query"
          return refuse.("query parameter #{param["name"]} uses style=#{style}") unless style == "form"
          return refuse.("query parameter #{param["name"]} uses explode=false") unless explode

          query << "#{param["name"]}#{"!" if param["required"]}"
        when "header"
          header[param["name"]] = "#{Keiyaku.snake(param["name"])}#{"!" if param["required"]}"
        else
          return refuse.("#{param["in"]} parameters are not supported")
        end
      end

      hint = op["x-keiyaku-paginate"]
      if hint && (problem = pagination_problem(hint, query))
        return refuse.("x-keiyaku-paginate: #{problem}")
      end

      body = form = multipart = content_type = nil
      if (request_body = resolve(op["requestBody"]))
        content = request_body["content"] || {}
        json = content.keys.find { _1.include?("json") }
        binary = content.keys.find { _1 == "application/octet-stream" || content[_1].dig("schema", "format") == "binary" }

        if json
          body = type_for(content[json]["schema"], "#{name}_body", deps)
        elsif content.key?("application/x-www-form-urlencoded")
          form = type_for(content["application/x-www-form-urlencoded"]["schema"], "#{name}_body", deps)
        elsif content.key?("multipart/form-data")
          multipart = multipart_type(content["multipart/form-data"]["schema"] || {}, "#{name}_body", deps)
        elsif binary
          body = ":binary"
          content_type = binary
        else
          return refuse.("request body is #{content.keys.join(", ")}")
        end
      end

      into, errors = nil, {}
      (op["responses"] || {}).each do |status, response|
        response = resolve(response)
        content = response["content"] || {}
        json = content.keys.find { _1.include?("json") }
        schema = json && content[json]["schema"]

        if status.to_i.between?(200, 299)
          next unless schema

          into ||= type_for(schema, "#{name}_result", deps)
          @notes << "#{name}: response is #{content.keys.join(", ")}, only #{json} is decoded" if json.nil? && content.any?
        elsif schema
          errors[status == "default" ? ":default" : status] = type_for(schema, "#{name}_error", deps)
        end
      end

      if into.nil? && (op["responses"] || {}).any? { |s, r| s.to_i.between?(200, 299) && (resolve(r)["content"] || {}).any? }
        @notes << "#{name}: success response has no JSON representation, returns the raw body"
      end

      { name:, verb:, template:, query:, header:, types:, body:, form:, multipart:, content_type:, into:,
        errors:, hint:, paginate: (hint && hash_source(hint)),
        security: (op["security"] == [] ? "false" : nil), summary: op["summary"], deps: }
    end

    # A hint that names a parameter the operation does not have would produce a
    # client that pages forever, so it is refused like any other construct that
    # cannot be honoured.
    def pagination_problem(hint, query)
      by = hint["by"].to_s
      names = query.map { _1.delete_suffix("!") }

      if !PAGINATION.include?(by)
        "unknown strategy #{hint["by"].inspect}, expected one of #{PAGINATION.join(", ")}"
      elsif (wrong = %w[param size].find { hint[_1] && !names.include?(hint[_1]) })
        "#{wrong} #{hint[wrong].inspect} is not a query parameter of this operation"
      elsif by != "link" && hint["param"].nil?
        "by: #{by} needs the name of the parameter to advance"
      elsif by == "cursor" && hint["next"].nil?
        "by: cursor needs the response field the next cursor comes from"
      end
    end

    def hash_source(hint)
      "{ #{hint.map { |key, value| "#{key}: #{key == "by" ? ":#{value}" : value.inspect}" }.join(", ")} }"
    end

    # A multipart body always gets its own type, even where the document points
    # at a shared component: `format: binary` means a file here and a plain
    # string everywhere else, and one model cannot mean both.
    def multipart_type(schema, context, deps)
      schema = merge_all_of(resolve(schema))
      return type_for(schema, context, deps) unless schema["properties"]

      hoist(context, schema, deps, upload: true) || ":any"
    end

    # --- output -------------------------------------------------------------

    def sorted_models
      ordered, seen = [], {}
      visit = lambda do |const|
        return if seen[const]

        seen[const] = :visiting
        @deps.fetch(const, []).each { |dep| visit.(dep) unless seen[dep] == :visiting }
        seen[const] = true
        ordered << const
      end
      @models.each_key { visit.(_1) }
      ordered
    end

    # The fields go in a Hash of their own rather than as keywords beside
    # `required:` and `from:`, because they are the API's names and not ours:
    # a DIDComm message has a property called `from`.
    def model_options(model)
      options = []
      options << "required: %i[#{model.required.join(" ")}]" if model.required.any?
      options << "from: { #{model.from.map { |field, json| "#{field}: #{json.inspect}" }.join(", ")} }" if model.from.any?
      options
    end

    def types_source
      lines = sorted_models.map do |const|
        model = @models[const]
        next "  #{const} = #{model}" if model.is_a?(String)

        fields = model.fields.map { |field, type| "#{field}: #{type}" }
        options = model_options(model).map { ", #{_1}" }.join
        one_line = "  #{const} = Keiyaku.model({ #{fields.join(", ")} }#{options})"
        next one_line if one_line.length <= 110

        "  #{const} = Keiyaku.model({\n    #{fields.join(",\n    ")}\n  }#{options})"
      end

      <<~RUBY
        # frozen_string_literal: true
        #{HEADER}

        require "keiyaku/runtime"

        module #{@namespace}
        #{lines.join("\n")}
        end
      RUBY
    end

    def client_source(operations)
      lines = operations.map do |op|
        next "    unsupported :#{op[:name]}, #{op[:unsupported].inspect}" if op[:unsupported]

        args = [":#{op[:name]}", op[:template].inspect]
        args << "query: %i[#{op[:query].join(" ")}]" if op[:query].any?
        args << "header: { #{op[:header].map { |json, ruby| "#{json.inspect} => :#{ruby}" }.join(", ")} }" if op[:header].any?
        args << "body: #{op[:body]}" if op[:body]
        args << "form: #{op[:form]}" if op[:form]
        args << "multipart: #{op[:multipart]}" if op[:multipart]
        args << "content_type: #{op[:content_type].inspect}" if op[:content_type]
        args << "into: #{op[:into]}" if op[:into]
        args << "errors: { #{op[:errors].map { |status, type| "#{status} => #{type}" }.join(", ")} }" if op[:errors].any?
        args << "paginate: #{op[:paginate]}" if op[:paginate]
        args << "security: false" if op[:security]

        "    #{op[:verb].ljust(6)} #{args.join(", ")}"
      end

      <<~RUBY
        # frozen_string_literal: true
        #{HEADER}

        require_relative "types"

        module #{@namespace}
          class Client < Keiyaku::Client
            server #{@spec.dig("servers", 0, "url").inspect}
        #{"    security(#{@security})\n" if @security}
        #{lines.join("\n")}
          end
        end
      RUBY
    end

    RBS_SCALARS = {
      ":bool" => "bool", ":any" => "untyped", ":binary" => "String",
      ":upload" => "Keiyaku::Upload | IO"
    }.freeze

    def rbs_type(source)
      return "Array[#{rbs_type(source[1..-2].strip)}]" if source.start_with?("[")
      return "Hash[String, #{rbs_type(source[/=>(.*)}/m, 1].strip)}]" if source.start_with?("{")

      # A named union is referred to by its alias; an inline one is spelled out.
      if (expansion = @unions[source])
        return source.start_with?("Keiyaku::OneOf[") ? expansion : Keiyaku.snake(source)
      end

      RBS_SCALARS[source] || source
    end

    # What the enumerator yields: the element of the array being paged over,
    # which is either the response itself or a field of the envelope.
    def paginate_element(op)
      source = op[:into]
      if (items = op[:hint]["items"])
        model = @models[source]
        return "untyped" unless model.is_a?(Model)

        source = model.fields[Keiyaku.snake(items)]
      end

      source.to_s.start_with?("[") ? rbs_type(source[1..-2].strip) : "untyped"
    end

    # RBS has no constant that stands for a union, so a union component becomes
    # a type alias for signatures to use, plus the constant itself for callers
    # that reach for `Event.cast`.
    def union_rbs(const)
      source = @models[const]
      constant =
        if source.start_with?("Keiyaku::OneOf[") then "Keiyaku::OneOf"
        elsif source == ":any" then "Symbol"
        else "untyped" # a union that collapsed to one type, so the constant is that type
        end

      "  type #{Keiyaku.snake(const)} = #{@unions[const]}\n  #{const}: #{constant}"
    end

    def rbs_source(operations)
      models = sorted_models.map do |const|
        model = @models[const]
        next union_rbs(const) if model.is_a?(String)

        readers = model.fields.map do |field, type|
          "    attr_reader #{field}: #{rbs_type(type)}#{"?" unless model.required.include?(field)}"
        end
        <<~RBS.chomp
            class #{const} < ::Data
          #{readers.join("\n")}
              def self.cast: (untyped, ?String) -> #{const}
              def to_json_hash: () -> Hash[String, untyped]
            end
        RBS
      end

      methods = operations.map do |op|
        next "    def #{op[:name]}: (*untyped) -> bot  # not generated: #{op[:unsupported]}" if op[:unsupported]

        types = op[:types]
        positional = op[:template].scan(/\{(\w+)\}/).flatten.map do |param|
          "#{rbs_type(types[param] || ":any")} #{Keiyaku.snake(param)}"
        end
        payload = op[:body] || op[:form] || op[:multipart]
        positional << "#{rbs_type(payload)} body" if payload

        keyword = lambda do |json_name, declared|
          required = declared.end_with?("!")
          type = rbs_type(types[json_name] || ":any")
          "#{"?" unless required}#{Keiyaku.snake(declared.delete_suffix("!"))}: #{type}#{"?" unless required}"
        end
        keywords = op[:query].map { keyword.(_1.delete_suffix("!"), _1) } +
                   op[:header].map { |json, ruby| keyword.(json, ruby) }
        arguments = (positional + keywords).join(", ")
        signature = "    def #{op[:name]}: (#{arguments}) -> #{op[:into] ? rbs_type(op[:into]) : "untyped"}"
        next signature unless op[:paginate]

        element = paginate_element(op)
        "#{signature}\n    def #{op[:name]}_each: (#{arguments}) " \
          "?{ (#{element}) -> void } -> Enumerator[#{element}, void]"
      end

      <<~RBS
        #{HEADER}

        module #{@namespace}
        #{models.join("\n\n")}

          class Client < Keiyaku::Client
        #{methods.join("\n")}
          end
        end
      RBS
    end
  end
end
