# frozen_string_literal: true
# Generated by keiyaku 0.1.0. Edits will be overwritten.

require_relative "types"

module Petstore
  class Client < Keiyaku::Client
    server "https://petstore3.swagger.io/api/v3"
    security({ petstore_auth: :bearer, api_key: { header: "api_key" } })

    put    :update_pet, "/pet", body: Pet, body_required: true, into: Pet, security: :petstore_auth
    post   :add_pet, "/pet", body: Pet, body_required: true, into: Pet, security: :petstore_auth
    get    :find_pets_by_status, "/pet/findByStatus", query: %i[status], required: %i[status], into: [Pet], security: :petstore_auth
    get    :find_pets_by_tags, "/pet/findByTags", query: %i[tags], required: %i[tags], into: [Pet], security: :petstore_auth
    get    :get_pet_by_id, "/pet/{petId}", into: Pet, security: [[:api_key], [:petstore_auth]]
    post   :update_pet_with_form, "/pet/{petId}", query: %i[name status], into: Pet, security: :petstore_auth
    delete :delete_pet, "/pet/{petId}", header: { "api_key" => :api_key }, security: :petstore_auth
    post   :upload_file, "/pet/{petId}/uploadImage", query: %i[additionalMetadata], body: :binary, content_type: "application/octet-stream", into: ApiResponse, security: :petstore_auth
    get    :get_inventory, "/store/inventory", into: { String => Integer }, security: :api_key
    post   :place_order, "/store/order", body: Order, into: Order
    get    :get_order_by_id, "/store/order/{orderId}", into: Order
    delete :delete_order, "/store/order/{orderId}"
    post   :create_user, "/user", body: User, into: User
    post   :create_users_with_list_input, "/user/createWithList", body: [User], into: User
    get    :login_user, "/user/login", query: %i[username password], into: String
    get    :logout_user, "/user/logout"
    get    :get_user_by_name, "/user/{username}", into: User
    put    :update_user, "/user/{username}", body: User
    delete :delete_user, "/user/{username}"
  end
end
