# frozen_string_literal: true
# Generated by keiyaku 0.1.0. Edits will be overwritten.

require_relative "types"

module Widgets
  class Client < Keiyaku::Client
    server "https://api.widgets.test/v1"
    security(:bearer)

    unsupported :list_widgets, "query parameter filter uses style=deepObject"
    post   :create_widget, "/widgets", body: Widget, into: Widget, errors: { 422 => Problem }
    get    :get_widget, "/widgets/{id}", into: Widget, errors: { :default => Problem }
    post   :upload_photo, "/widgets/{id}/photo", multipart: UploadPhotoBody, into: Widget
    get    :search_widgets, "/widgets/search", query: %i[q! cursor], into: SearchWidgetsResult, paginate: { by: :cursor, param: "cursor", next: "next_cursor", items: "items" }
    get    :widget_feed, "/widgets/feed", into: [Widget], paginate: { by: :link }
    get    :list_events, "/widgets/{id}/events", query: %i[limit offset], into: [Event], paginate: { by: :offset, param: "offset", size: "limit", per: 2 }
  end
end
