# frozen_string_literal: true
# Generated by keiyaku 0.1.0. Edits will be overwritten.

require "keiyaku/runtime"

module Widgets
  Widget = Keiyaku.model(
    id: Integer,
    created_at: Time,
    labels: { String => String },
    retired: :bool,
    required: %i[id created_at],
    from: { created_at: "created_at" }
  )
  Problem = Keiyaku.model(
    detail: String,
    trace_id: String,
    required: %i[detail],
    from: { trace_id: "trace_id" }
  )
end
