# frozen_string_literal: true
# Generated by keiyaku 0.1.0. Edits will be overwritten.

require "keiyaku/runtime"

module Widgets
  Widget = Keiyaku.model({
    id: Integer,
    created_at: Time,
    labels: { String => String },
    retired: :bool
  }, required: %i[id created_at], from: { created_at: "created_at" })
  Problem = Keiyaku.model({
    detail: String,
    trace_id: String,
    source: :any
  }, required: %i[detail], from: { trace_id: "trace_id" })
  WidgetCreated = Keiyaku.model({ kind: String, widget: Widget }, required: %i[kind widget])
  WidgetRetired = Keiyaku.model({ kind: String, id: Integer, reason: String }, required: %i[kind id])
  ImportQueued = Keiyaku.model({ job_id: String }, required: %i[job_id], from: { job_id: "job_id" })
  Note = Keiyaku.model({ text: String, locale: String }, required: %i[text])
  Event = Keiyaku::OneOf[WidgetCreated, WidgetRetired, on: "kind", map: { "created" => WidgetCreated, "retired" => WidgetRetired }]
  UploadPhotoBody = Keiyaku.model({ file: :upload, caption: String, tags: [String] }, required: %i[file])
  SearchWidgetsFilter = Keiyaku.model({ status: String, since: Time })
  SearchWidgetsResult = Keiyaku.model({
    items: [Widget],
    next_cursor: String
  }, from: { next_cursor: "next_cursor" })
end
