# frozen_string_literal: true
# Generated by keiyaku 0.1.0. Edits will be overwritten.

require_relative "types"

module Sidecar
  class Client < Keiyaku::Client
    server nil

    post   :post_didcomm_pack_encrypted, "/didcomm/pack/encrypted", body: PostDidcommPackEncryptedBody, into: PostDidcommPackEncryptedResult, errors: { 400 => PostDidcommPackEncryptedError }
    post   :post_didcomm_pack_signed, "/didcomm/pack/signed", body: PostDidcommPackSignedBody, into: PostDidcommPackSignedResult, errors: { 400 => PostDidcommPackEncryptedError }
    post   :post_didcomm_pack_plaintext, "/didcomm/pack/plaintext", body: PostDidcommPackPlaintextBody, into: PostDidcommPackPlaintextResult, errors: { 400 => PostDidcommPackEncryptedError }
    post   :post_didcomm_unpack, "/didcomm/unpack", body: PostDidcommUnpackBody, into: PostDidcommUnpackResult, errors: { 400 => PostDidcommPackEncryptedError }
    post   :post_did_resolve, "/did/resolve", body: PostDidResolveBody, into: PostDidResolveResult, errors: { 400 => PostDidResolveResult, 404 => PostDidResolveResult }
    post   :post_did_didcomm_doc, "/did/didcomm-doc", body: PostDidResolveBody, into: PostDidDidcommDocResult, errors: { 400 => PostDidcommPackEncryptedError, 404 => PostDidcommPackEncryptedError }
    post   :post_did_peer_4, "/did/peer/4", body: PostDidPeer4Body, into: PostDidPeer4Result, errors: { 400 => PostDidcommPackEncryptedError }
    post   :post_did_peer_4_create, "/did/peer/4/create", body: PostDidPeer4CreateBody, into: PostDidPeer4CreateResult, errors: { 400 => PostDidcommPackEncryptedError }
    post   :post_did_peer_4_resolve_short, "/did/peer/4/resolve-short", body: PostDidPeer4ResolveShortBody, into: PostDidResolveResult, errors: { 400 => PostDidResolveResult }
    get    :get_health, "/health", into: GetHealthResult
  end
end
