# frozen_string_literal: true
# Generated by keiyaku 0.1.0. Edits will be overwritten.

require "keiyaku/runtime"

module Sidecar
  PostDidcommPackEncryptedBodyMessageAttachments = Keiyaku.model({
    data: :any,
    id: String,
    description: String,
    filename: String,
    media_type: String,
    format: String,
    lastmod_time: Float,
    byte_count: Float
  }, required: %i[data], from: { media_type: "media_type", lastmod_time: "lastmod_time", byte_count: "byte_count" })
  PostDidcommPackEncryptedBodyMessage = Keiyaku.model({
    id: String,
    typ: String,
    type: String,
    body: :any,
    from: String,
    to: [String],
    thid: String,
    pthid: String,
    created_time: Float,
    expires_time: Float,
    from_prior: String,
    attachments: [PostDidcommPackEncryptedBodyMessageAttachments]
  }, required: %i[id typ type body], from: { created_time: "created_time", expires_time: "expires_time", from_prior: "from_prior" })
  PostDidcommPackEncryptedBodyOptions = Keiyaku.model({
    protect_sender: :bool,
    forward: :bool,
    forward_headers: [[:any]],
    messaging_service: String,
    enc_alg_auth: String,
    enc_alg_anon: String
  }, from: { protect_sender: "protect_sender", forward_headers: "forward_headers", messaging_service: "messaging_service", enc_alg_auth: "enc_alg_auth", enc_alg_anon: "enc_alg_anon" })
  PostDidcommPackEncryptedBodyDidDocsVerificationMethod = Keiyaku.model({
    id: String,
    type: String,
    controller: String,
    public_key_jwk: { String => :any },
    public_key_multibase: String,
    public_key_base58: String
  }, required: %i[id type controller])
  PostDidcommPackEncryptedBodyDidDocsService = Keiyaku.model({
    id: String,
    type: String,
    service_endpoint: :any
  }, required: %i[id type service_endpoint])
  PostDidcommPackEncryptedBodyDidDocs = Keiyaku.model({
    id: String,
    key_agreement: [String],
    authentication: [String],
    verification_method: [PostDidcommPackEncryptedBodyDidDocsVerificationMethod],
    service: [PostDidcommPackEncryptedBodyDidDocsService]
  }, required: %i[id key_agreement authentication verification_method service])
  PostDidcommPackEncryptedBodySecrets = Keiyaku.model({
    id: String,
    type: String,
    private_key_jwk: { String => :any },
    private_key_multibase: String,
    private_key_base58: String
  }, required: %i[id type])
  PostDidcommPackEncryptedBody = Keiyaku.model({
    message: PostDidcommPackEncryptedBodyMessage,
    to: String,
    from: String,
    sign_by: String,
    options: PostDidcommPackEncryptedBodyOptions,
    did_docs: [PostDidcommPackEncryptedBodyDidDocs],
    secrets: [PostDidcommPackEncryptedBodySecrets]
  }, required: %i[message to], from: { sign_by: "sign_by" })
  PostDidcommPackEncryptedResultMetadataMessagingService = Keiyaku.model({
    id: String,
    service_endpoint: String
  }, required: %i[id service_endpoint], from: { service_endpoint: "service_endpoint" })
  PostDidcommPackEncryptedResultMetadata = Keiyaku.model({
    messaging_service: PostDidcommPackEncryptedResultMetadataMessagingService,
    from_kid: String,
    sign_by_kid: String,
    to_kids: [String]
  }, required: %i[to_kids], from: { messaging_service: "messaging_service", from_kid: "from_kid", sign_by_kid: "sign_by_kid", to_kids: "to_kids" })
  PostDidcommPackEncryptedResult = Keiyaku.model({
    packed_message: String,
    delivery_endpoint: String,
    metadata: PostDidcommPackEncryptedResultMetadata
  }, required: %i[packed_message delivery_endpoint metadata])
  PostDidcommPackEncryptedError = Keiyaku.model({
    error: String,
    message: String
  }, required: %i[error message])
  PostDidcommPackSignedBody = Keiyaku.model({
    message: PostDidcommPackEncryptedBodyMessage,
    sign_by: String,
    did_docs: [PostDidcommPackEncryptedBodyDidDocs],
    secrets: [PostDidcommPackEncryptedBodySecrets]
  }, required: %i[message sign_by], from: { sign_by: "sign_by" })
  PostDidcommPackSignedResultMetadata = Keiyaku.model({
    sign_by_kid: String
  }, required: %i[sign_by_kid], from: { sign_by_kid: "sign_by_kid" })
  PostDidcommPackSignedResult = Keiyaku.model({
    packed_message: String,
    metadata: PostDidcommPackSignedResultMetadata
  }, required: %i[packed_message metadata])
  PostDidcommPackPlaintextBody = Keiyaku.model({
    message: PostDidcommPackEncryptedBodyMessage,
    did_docs: [PostDidcommPackEncryptedBodyDidDocs]
  }, required: %i[message])
  PostDidcommPackPlaintextResult = Keiyaku.model({ packed_message: String }, required: %i[packed_message])
  PostDidcommUnpackBodyOptions = Keiyaku.model({
    expect_decrypt_by_all_keys: :bool,
    unwrap_re_wrapping_forward: :bool
  }, from: { expect_decrypt_by_all_keys: "expect_decrypt_by_all_keys", unwrap_re_wrapping_forward: "unwrap_re_wrapping_forward" })
  PostDidcommUnpackBody = Keiyaku.model({
    message: String,
    options: PostDidcommUnpackBodyOptions,
    did_docs: [PostDidcommPackEncryptedBodyDidDocs],
    secrets: [PostDidcommPackEncryptedBodySecrets]
  }, required: %i[message])
  PostDidcommUnpackResultMetadata = Keiyaku.model({
    encrypted: :bool,
    authenticated: :bool,
    non_repudiation: :bool,
    anonymous_sender: :bool,
    re_wrapped_in_forward: :bool,
    encrypted_from_kid: String,
    encrypted_to_kids: [String],
    sign_from: String,
    from_prior_issuer_kid: String,
    enc_alg_auth: String,
    enc_alg_anon: String,
    sign_alg: String,
    signed_message: String,
    from_prior: :any
  }, required: %i[encrypted authenticated non_repudiation anonymous_sender re_wrapped_in_forward], from: { non_repudiation: "non_repudiation", anonymous_sender: "anonymous_sender", re_wrapped_in_forward: "re_wrapped_in_forward", encrypted_from_kid: "encrypted_from_kid", encrypted_to_kids: "encrypted_to_kids", sign_from: "sign_from", from_prior_issuer_kid: "from_prior_issuer_kid", enc_alg_auth: "enc_alg_auth", enc_alg_anon: "enc_alg_anon", sign_alg: "sign_alg", signed_message: "signed_message", from_prior: "from_prior" })
  PostDidcommUnpackResult = Keiyaku.model({
    message: PostDidcommPackEncryptedBodyMessage,
    from: String,
    verified_from: String,
    sender_verified: :bool,
    encrypted: :bool,
    metadata: PostDidcommUnpackResultMetadata
  }, required: %i[message from verified_from sender_verified encrypted metadata])
  PostDidResolveBody = Keiyaku.model({ did: String }, required: %i[did])
  PostDidResolveResultDidResolutionMetadata = Keiyaku.model({
    content_type: String,
    error: String,
    message: String
  })
  PostDidResolveResult = Keiyaku.model({
    did_document: :any,
    did_document_metadata: { String => :any },
    did_resolution_metadata: PostDidResolveResultDidResolutionMetadata
  }, required: %i[did_document did_document_metadata did_resolution_metadata])
  PostDidDidcommDocResult = Keiyaku.model({
    did_doc: PostDidcommPackEncryptedBodyDidDocs
  }, required: %i[did_doc])
  PostDidPeer4Body = Keiyaku.model({ document: { String => :any } }, required: %i[document])
  PostDidPeer4Result = Keiyaku.model({
    did: String,
    short_did: String,
    did_document: :any,
    short_did_document: :any,
    didcomm_did_doc: PostDidcommPackEncryptedBodyDidDocs
  }, required: %i[did short_did did_document short_did_document didcomm_did_doc])
  PostDidPeer4CreateBody = Keiyaku.model({ keys: [String], service: String })
  PostDidPeer4CreateResult = Keiyaku.model({
    did: String,
    short_did: String,
    input_document: { String => :any },
    did_document: :any,
    short_did_document: :any,
    didcomm_did_doc: PostDidcommPackEncryptedBodyDidDocs,
    secrets: [PostDidcommPackEncryptedBodySecrets]
  }, required: %i[did short_did input_document did_document short_did_document didcomm_did_doc secrets])
  PostDidPeer4ResolveShortBody = Keiyaku.model({
    document: { String => :any },
    did: String
  }, required: %i[document])
  GetHealthResult = Keiyaku.model({ status: String }, required: %i[status])
end
